### PR TITLE
Agg vs gold fixes

### PR DESCRIPTION
**Pull request by drammock**
This adds a test script to compare the "gold standard" database dump with the output of the aggregation script, and fixes some of the problems that it reveals (though not yet all).  Should not be merged yet, until we figure out what to do about the remaning discrepancies between `agg` and `gold`.  Note that most of the remaining discrepancies are due to the UPSID "dental|alveolar" agnosticism.

You can test this locally with 
`git checkout -b testAggGold drammock/agg-vs-gold-fixes`
(assuming you have a remote called `drammock` that points to `drammock/phoible` repo).

### CODE REVIEW

**Comment by drammock** [comment]
Closes #49

**Comment by drammock** [comment]
This now tests gold standard vs. the aggregation RData output with all of the ISO code fixes in place (i.e., it behaves as if [this PR](https://github.com/bambooforest/phoible/pull/1) and #68 have both been merged already). With those ISO code fixes in place, the agg vs. gold disparity is down to 4 languages present in gold but not in agg, and 15 inventories with discrepancies between agg & gold.

**Comment by drammock** [comment]
@bambooforest, it's probably time to merge this before things get any more tangled.  There are still a few agg vs gold differences, but they'll be easier to see once this is merged and I can look at it afresh.

**Comment by bambooforest** [comment]
I agree. Will review and merge.

**Pull request merged**
